import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WebSocketProvider from "./context/ws";
import UserProvider from "./context/user";
import ChatProvider from "./context/rooms";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <UserProvider>
        <ChatProvider>
          <WebSocketProvider >
            <body className={inter.className}>{children}</body>
          </WebSocketProvider>
        </ChatProvider>
      </UserProvider>
    </html>
  );
}
