run-docker:
	docker-compose -d up

postgresinit:
	docker run --name postgres15 -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -d postgres:15-alpine

postgres:
	docker exec -it postgres15 psql

createdb:
	docker exec -it postgres15 createdb --username=postgres --owner=root go-chat

dropdb:
	docker exec -it postgres15 dropdb go-chat

migrateup:
	migrate -path internal/db/migrations -database "postgresql://postgres:password@localhost:5432/go-chat?sslmode=disable" -verbose up

migratedown:
	migrate -path internal/db/migrations -database "postgresql://postgres:password@localhost:5432/go-chat?sslmode=disable" -verbose down

.PHONY: postgresinit postgres createdb dropdb migrateup migratedown run-docker